name: Daily Agent Run

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight UTC
  workflow_dispatch:      # also allows manual trigger

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run agent pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          A4F_API_KEY: ${{ secrets.A4F_API_KEY }}
          A4F_BASE_URL: ${{ secrets.A4F_BASE_URL }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python agent_runner.py  # this should output final_output.csv

      - name: Upload final CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-csv-output
          path: final_output.csv
